name: Daily Bonus

on:
  push:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    environment: checkin_environment

    env:
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      MUSIC_CELLPHONE: ${{ secrets.MUSIC_CELLPHONE }}
      MUSIC_PASSWORD: ${{ secrets.MUSIC_PASSWORD }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      FFXIV_USERNAME: ${{ secrets.FFXIV_USERNAME }}
      FFXIV_PASSWORD: ${{ secrets.FFXIV_PASSWORD }}
      FFXIV_AREA_NAME: ${{ secrets.FFXIV_AREA_NAME }}
      FFXIV_SERVER_NAME: ${{ secrets.FFXIV_SERVER_NAME }}
      FFXIV_ROLE_NAME: ${{ secrets.FFXIV_ROLE_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Echo current time
        run: timedatectl
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Yamibo
        run: python ./Yamibo/yamibo_checkin.py
        if: always()
