name: Daily Bonus

on:
  push:
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    environment: checkin_environment

    env:
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
    steps:
      - uses: actions/checkout@v2
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Echo current time
        run: timedatectl
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Yamibo
        run: python ./Yamibo/yamibo_checkin.py
        if: always()
